set -g prefix C-z
unbind C-b
bind C-z send-prefix

set -g mouse on

set -g status-right ""
set -g status-right "#(cat /sys/class/power_supply/BAT0/capacity)%% | %Y-%m-%d %H:%M"

set -g window-status-format "#I:#W"
set -g window-status-current-format "#[bold]#I:#W"
set -g window-status-current-style "fg=orange"

set -g base-index 1
setw -g pane-base-index 1

set -g status-style bg=default
